IF EXISTS (SELECT name FROM sys.databases WHERE name = 'TaxiTrips')
BEGIN
    ALTER DATABASE TaxiTrips SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE TaxiTrips;
END
CREATE DATABASE TaxiTrips;